name: meat_gradation_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+11
  tflite_flutter: ^0.9.0
  permission_handler: ^10.2.0
  tflite: ^1.1.2
  opencv_4: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/chicken_model.tflite
    - assets/models/fish_model.tflite
    - assets/models/prawn_model.tflite
    - assets/models/meat_classifier.tflite
    - assets/models/meat_classifier_labels.txt
    - assets/images/openLogo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

