name: meat_gradation_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+11
  tflite_flutter: ^0.9.0
  permission_handler: ^10.2.0
  tflite: ^1.1.2
  camera: ^0.10.3+2
  path_provider: ^2.0.14
  path: ^1.8.2
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/models/chicken_model.tflite
    - assets/models/fish_model.tflite
    - assets/models/prawn_model.tflite
    - assets/models/chicken_model_labels.txt
    - assets/models/fish_model_labels.txt
    - assets/models/prawn_model_labels.txt
    - assets/models/meat_classifier.tflite
    - assets/models/meat_classifier_labels.txt
    - assets/images/openLogo.png

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf

